### ISSUE TITLE
README does not mention dependence on ts-node for TypeScript mock files

### ISSUE THREAD

**Issue by psimk** [mediamonks/monck#1]
Both the `README.md` and the example from `examples` are showcasing mock files defined in TypeScript. However, neither does a great job at explaining that in order for `monck` to execute the TypeScript mocks, we need to preload something that can handle TypeScript modules (e.g. `ts-node`).

I created a reproduction repository https://github.com/psimk/monck-ts-node-repro :
* running `npm run start` will fail with
> ✖  error     Mock file parse failed: Cannot use import statement outside a module
* running `npm run start:ts-node` successfully runs the server

---

It should be made clear in the `README.md` that you need to either first compile your mock files to TS or preload a TypeScript module handler. However, both options make it more annoying/time consuming to setup and use `monck`, so instead I would suggest to register a TypeScript module loader in `monck`, so it is able to handle TypeScript mocks without any additional configuration on the part of the user.

**Comment by ThaNarie** [comment]
I think this has been solved by #4 as well?

**Comment by psimk** [comment]
> I think this has been solved by #4 as well?

Correct.
